# style syntax
#   color: rgb(base10, base10, base10)
#   color: #RGB (base 16)
#   color: #RRGGBB (base 16)
#   bold: bool
#   italic: bool
#   underline: bool
#   dimmed: bool


# the style of the filename in the first-line
[theme.file_header]
color = "#56b6c2"
bold = true
italic = true

# the style of the filename in each result
[theme.file_name]
color = "#AAAAAA"

# the style of the row/col in each result
[theme.location]
dimmed = true

# the style of the missing docs message
[theme.message]
color = "#999999"

# the style of the highlighted code
[theme.highlight_code]
color = "#e8a"
italic = true

# the style of the normal code
# [theme.code]

# styles for matching specific 'kinds' of items
# [theme.kinds.associated_constant]
# [theme.kinds.associated_function]
# [theme.kinds.associated_type]
# [theme.kinds.constant]
# [theme.kinds.crate]
# [theme.kinds.enum]
# [theme.kinds.function]
# [theme.kinds.macro]
# [theme.kinds.method]
# [theme.kinds.struct]
# [theme.kinds.struct_field]
# [theme.kinds.trait]
# [theme.kinds.type_alias]
# [theme.kinds.variant]
# [theme.kinds.static]
